version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-gym-manager

hooks:
  ApplicationStop:
    - location: scripts/on_application_stop.sh
      timeout: 300
      runas: ubuntu

  BeforeInstall:
    - location: scripts/on_before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/on_application_start.sh
      timeout: 300
      runas: ubuntu